### ISSUE TITLE
Net8 MAUI Version

### ISSUE THREAD

**Issue by Elinares-82** [CleverTap/clevertap-xamarin#13]
We are moving our e-commerce platform to MAUI. We are almost ready however the only component that is not working is the CleverTap one. In case there is no plan to create the version for NET MAUI we will be force to remove the CleverTap integration. Also we tried to create the binding, but the generated assembly does not have several properties and methods.

**Comment by darshanclevertap** [comment]
@Elinares-82 
So our Android DLL is compatible with .NET 8 with certain tweaks. Could you please open a support ticket via our [Help Center](https://help.clevertap.com/hc/en-us)? Please mention this GitHub issue. Please mention the .NET version you are using, the errors you faced during creation of the bindings, and this will be routed to our SDK team who will be able to help out.

**Comment by Elinares-82** [comment]
> @Elinares-82 So our Android DLL is compatible with .NET 8 with certain tweaks. Could you please open a support ticket via our [Help Center](https://help.clevertap.com/hc/en-us)? Please mention this GitHub issue. Please mention the .NET version you are using, the errors you faced during creation of the bindings, and this will be routed to our SDK team who will be able to help out.

Thanks for your response. This is not just for Android is also for iOS. We are trying event with the MAUI team make the new Binding. But the generated assemblies are no working properly.

**Comment by darshanclevertap** [comment]
@Elinares-82 Yes we are working on the iOS side of things too. A support ticket will route you directly to our SDK team for this.

**Comment by Elinares-82** [comment]
> @Elinares-82 Yes we are working on the iOS side of things too. A support ticket will route you directly to our SDK team for this.

Thanks!, Done.

**Comment by Elinares-82** [comment]
> > @Elinares-82 Yes we are working on the iOS side of things too. A support ticket will route you directly to our SDK team for this.
> 
> Thanks!, Done.

I'm attaching the project that I created to bind the Android part.

[CleverTap.Bindings.Android.zip](https://github.com/CleverTap/clevertap-xamarin/files/14316564/CleverTap.Bindings.Android.zip)

**Comment by Elinares-82** [comment]
> > > @Elinares-82 Yes we are working on the iOS side of things too. A support ticket will route you directly to our SDK team for this.
> > 
> > 
> > Thanks!, Done.
> 
> I'm attaching the project that I created to bind the Android part.
> 
> [CleverTap.Bindings.Android.zip](https://github.com/CleverTap/clevertap-xamarin/files/14316564/CleverTap.Bindings.Android.zip)

I'm attaching a new version of the Android binding that compiles better, however, still not working , we are getting several issues like 

'CleverTapAPI.CoreState.get' is obsolete: 'While this member is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.'

And

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	JAVAC0000	 error: package com.clevertap.android.sdk does not exist
		com.clevertap.android.sdk.InAppNotificationButtonListener,
	NeighborStore.Mobile.App	F:\EMotionB2B\Mobile\Src\NeighborStore.Mobile\NeighborStore.Mobile.App\obj\Debug\net8.0-android\android\src\crc64eb54d68f575ea824\MainActivity.java	8		

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/f525532b-8064-4dff-b152-f18969e98ad0)


[CleverTap.Bindings.Android.zip](https://github.com/CleverTap/clevertap-xamarin/files/14317525/CleverTap.Bindings.Android.zip)

**Comment by Elinares-82** [comment]
> > > > @Elinares-82 Yes we are working on the iOS side of things too. A support ticket will route you directly to our SDK team for this.
> > > 
> > > 
> > > Thanks!, Done.
> > 
> > 
> > I'm attaching the project that I created to bind the Android part.
> > [CleverTap.Bindings.Android.zip](https://github.com/CleverTap/clevertap-xamarin/files/14316564/CleverTap.Bindings.Android.zip)
> 
> I'm attaching a new version of the Android binding that compiles better, however, still not working , we are getting several issues like
> 
> 'CleverTapAPI.CoreState.get' is obsolete: 'While this member is 'public', Google considers it internal API and reserves the right to modify or delete it in the future. Use at your own risk.'
> 
> And
> 
> Severity Code Description Project File Line Suppression State Details Error JAVAC0000 error: package com.clevertap.android.sdk does not exist com.clevertap.android.sdk.InAppNotificationButtonListener, NeighborStore.Mobile.App F:\EMotionB2B\Mobile\Src\NeighborStore.Mobile\NeighborStore.Mobile.App\obj\Debug\net8.0-android\android\src\crc64eb54d68f575ea824\MainActivity.java 8
> 
> ![image](https://private-user-images.githubusercontent.com/158092565/305593024-f525532b-8064-4dff-b152-f18969e98ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NTY3MTgsIm5iZiI6MTcwODU1NjQxOCwicGF0aCI6Ii8xNTgwOTI1NjUvMzA1NTkzMDI0LWY1MjU1MzJiLTgwNjQtNGRmZi1iMTUyLWYxODk2OWU5OGFkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMVQyMzAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTA0OWIyMTY3OTM4MzZkNTVkOTAxZmUyZDE5NjQwMmMzY2ExZDQ2NjQ2MzFhOGFiNTdiZDc3MTgwZjdkM2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XrYdRCH_moZsz-BUcHOJdorX3PyyrgOc_s6gjsKkxNA)
> 
> [CleverTap.Bindings.Android.zip](https://github.com/CleverTap/clevertap-xamarin/files/14317525/CleverTap.Bindings.Android.zip)

[CleverTap.Bindings.Android.zip](https://github.com/CleverTap/clevertap-xamarin/files/14366081/CleverTap.Bindings.Android.zip)

I'm attaching the CleverTap Net8 Android Binding. Please let me know if this version works as expected to add to my project. Otherwise, we will remove the clever tap integration from our platform while an official assembly is released.

**Comment by Elinares-82** [comment]
> tweaks

Do you know why vs is displaying this waning message? 

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/54bfac05-d9e6-4ef0-8a23-487b16164cef)

**Comment by Elinares-82** [comment]
Hi. is there good news here? I was able to make the Android side worked, but we are waiting for the iOS part.

**Comment by Elinares-82** [comment]
> Hi. is there good news here? I was able to make the Android side worked, but we are waiting for the iOS part.

In addition to this, the following error is throwing the ios compilation:

1>Tool xcrun execution finished (exit code = 1).

1>Undefined symbols for architecture x86_64:

1>  "_OBJC_CLASS_$_CTInAppNotificationDisplayDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CTInAppPassThroughViewDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapDisplayUnitDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapDomainDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapFeatureFlagsDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapInAppNotificationDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapInboxViewControllerDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapProductConfigDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapPushNotificationDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapSyncDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>  "_OBJC_CLASS_$_CleverTapURLDelegate", referenced from:

1>     -exported_symbol[s_list] command line option

1>ld: symbol(s) not found for architecture x86_64
1>clang: error: linker command failed with exit code 1 (use -v to see invocation)

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error : clang++ exited with code 1:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error : Undefined symbols for architecture x86_64:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CTInAppNotificationDisplayDelegate", referenced from:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :      -exported_symbol[s_list] command line option

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CTInAppPassThroughViewDelegate", referenced from:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :      -exported_symbol[s_list] command line option

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CleverTapDisplayUnitDelegate", referenced from:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :      -exported_symbol[s_list] command line option

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CleverTapDomainDelegate", referenced from:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :      -exported_symbol[s_list] command line option

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CleverTapFeatureFlagsDelegate", referenced from:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :      -exported_symbol[s_list] command line option

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CleverTapInAppNotificationDelegate", referenced from:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :      -exported_symbol[s_list] command line option

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CleverTapInboxViewControllerDelegate", referenced from:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :      -exported_symbol[s_list] command line option

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CleverTapProductConfigDelegate", referenced from:

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :      -exported_symbol[s_list] command line option

1>C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\17.2.8004\targets\Xamarin.Shared.Sdk.targets(1559,3): error :   "_OBJC_CLASS_$_CleverTapPushNotificatio

**Comment by Elinares-82** [comment]
Any feedback here? Is there a release date for net8 MAUI?

**Comment by CTLalit** [comment]
Thanks for looking into android bindings part, it would be nice if you could raise a PR for the Android part. 
Let us share an update on this as we are already discussing this internally once we have a roadmap.

Are you guys deprecating Xamarin on May 1st as provided on their page and migrating to MAUI?

**Comment by Elinares-82** [comment]
> Thanks for looking into android bindings part, it would be nice if you could raise a PR for the Android part. Let us share an update on this as we are already discussing this internally once we have a roadmap.
> 
> Are you guys deprecating Xamarin on May 1st as provided on their page and migrating to MAUI?

Hi, I uploaded the code -(the hard part) so maybe is easy for you guys to merge with your repo. In the other hand we are waiting for de iOS one. Our movement to MAUI is in Paralyzed state because this. And we deprecated the XF version, but we were force to maintenance the XF until you guys can provide us de iOS binding. 

Please help us with the iOS binding to move forward.

**Comment by Elinares-82** [comment]
> Any feedback here? Is there a release date for net8 MAUI?

Any feedback here? Is there a release date for net8 MAUI?

**Comment by nishant-clevertap** [comment]
Hi @Elinares-82,
We will be releasing our iOS and Android .NET binding file by next week which will be compatible with .NET and MAUI apps. I will update you when release is done.

**Comment by Anush-Shand** [comment]
@Elinares-82 DotNet Bindings for iOS and Android have been released

NuGet package links
Android - https://www.nuget.org/packages/CleverTap.DotNet.Android.Binding/
iOS - https://www.nuget.org/packages/CleverTap.DotNet.iOS.Binding/

Marking this as closed. Feel free to reach out to us if you face any issues

**Comment by Elinares-82** [comment]
> @Elinares-82 DotNet Bindings for iOS and Android have been released
> 
> NuGet package links Android - https://www.nuget.org/packages/CleverTap.DotNet.Android.Binding/ iOS - https://www.nuget.org/packages/CleverTap.DotNet.iOS.Binding/
> 
> Marking this as closed. Feel free to reach out to us if you face any issues

Hi Anush-Sand, thanks so much we prepared everything in our side to release without CleverTap integration, however, tis are good Newses for us. We will add the references and let you guys know if all is in place.

**Comment by Elinares-82** [comment]
Hi , Did you test the Android binding?

As soon as I added the android binding, I got the following errors:

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/820dec08-17be-4fe5-a8d8-d8ee1d0fa1bc)

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/2301a742-ee6c-439f-af4d-0fb4db96b8b7)

As you can see the size of the older assembly is much different to the Net8 one

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/c1aee93f-f845-460e-bb6f-625c01d0e644)

Also, I reviewed the assembly, and nothing is in there.

![image](https://github.com/CleverTap/clevertap-xamarin/assets/158092565/00b5fc3d-192b-4437-82d1-dd461fc88e7d)

I attached and VS solution where I fixed all of this errors for the Android Binding. Please review the code that a provided you guys.
